### ISSUE TITLE
Please clarify License

### ISSUE THREAD

**Issue by dim** [ssttevee/go-av#1]
Hi,

This is a really great project but I would be hesitant to use (and help maintaining) it due to license uncertainty. On top of that, https://pkg.go.dev/github.com/ssttevee/go-av is also refusing to index it.

Would you be able to clarify the license you intend to use?

Thanks,
Dim

**Comment by ssttevee** [comment]
Thanks for letting me know, I've added a license

The docs doesn't seem to have updated right away, but it should work soon
